version: "3"
networks:
  idsnet:
      driver: bridge
      ipam:
        config:  
            - subnet: 192.168.1.0/26
          
services:
  idsngx:
    image: nginx
    networks:
        idsnet:
            ipv4_address: 192.168.1.31
    ports:
        - "80:80"       
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "${IDS_DATASPACE_DIR:-~/.ids}/nginx/conf.d:/etc/nginx/conf.d:ro"
    container_name: ids_ngx
    extra_hosts:
        - "ids.fzyun.io:${IDS_AM_HOST:-127.0.0.1}" 
  idsam:
    build:
        context: src/openam
    image: ${IDS_DOCKER_REG:-hub.fzyun.io:5000}/${IDS_DOCKER_REPO:-founder}/openam:${IDS_DOCKER_TAG:-latest}
    expose: 
        - "8080"
    volumes: 
        - "${IDS_DATASPACE_DIR:-~/.ids}/openam/instance1:/root/sso"
    container_name: ids_am
    ports:
        - "8080:8080"
    networks:
        idsnet:
            ipv4_address: 192.168.1.32
  idsdj:
    build:
        context: src/opendj
    image: ${IDS_DOCKER_REG:-hub.fzyun.io:5000}/${IDS_DOCKER_REPO:-founder}/opendj:${IDS_DOCKER_TAG:-latest}
    ports:
        - "1389:1389"
        - "1636:1636"
        - "4444:4444"
    container_name: ids_dj
    volumes: 
        - "${IDS_DATASPACE_DIR:-~/.ids}/opendj/instance1:/opt/opendj/instance"
    networks:
        idsnet:
            ipv4_address: 192.168.1.33
  idsidm:
    depends_on:
        - idsmysql
    build:
        context: src/openidm
    image: ${IDS_DOCKER_REG:-hub.fzyun.io:5000}/${IDS_DOCKER_REPO:-founder}/openidm:${IDS_DOCKER_TAG:-latest}
    ports: 
        - "8081:8080"
    container_name: ids_idm
    networks:
        idsnet:
            ipv4_address: 192.168.1.34
    volumes:
        - "${IDS_DATASPACE_DIR:-~/.ids}/openidm/instance1/conf:/opt/openidm/conf"
    command: ["./run.sh"]
  idsmysql:
    image: mysql:5.7
    ports:
        - 3333:3306
    environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD:-12345678}"
    container_name: ids_mysql
    networks:
        idsnet:
            ipv4_address: 192.168.1.35
    volumes:
        - "${IDS_DATASPACE_DIR:-~/.ids}/mysql/instance1:/var/lib/mysql"
        - "${IDS_DATASPACE_DIR:-~/.ids}/mysql/scripts/:/docker-entrypoint-initdb.d/:ro"
